### PR TITLE
fix refit bug

### LINKED ISSUE #71: improve robustness of image centering
I've found at least one case where in registration.anats_to_common, the center of undump.nii.gz is not in the matrix center, but well outside. this appears to be caused by 3drefit getting confused by poorly reconstructed data. in the end I found a solution by changing the data reconstruction, though luckily the mistake was on the RL axis so made little difference.

but in the long-term a replacement needs to be found for 3dUndump and 3drefit.
I guess this would be using nibabel to create a fake image with the same matrix size, and voxel dimensions as raw_heads_tstat.nii.gz, but somehow keeping the same axis orientations, and setting the center to be at the matrix center

### PR DESCRIPTION
**Pull request by salma1601**
fixes #71

### CODE REVIEW

**Comment by salma1601** [comment]
@nadkarni-na I think now it will work. can you check with this fix ?

**Comment by nadkarni-na** [comment]
lol this is the same workaround used in anats_to_common. is anyone any closer to finding out what the underlying nipype issue is?

**Comment by salma1601** [comment]
Yes it is the same problem and I think it is rather me misunderstanding how the interfaces work than a nipype issue. I am using a unique instanciation of each interface and then just calling it several times. So inputs that are not changed explicitly conserve their last values

**Comment by salma1601** [comment]
could you please do a review so that I merge it ?

**Pull request merged**
