### PR TITLE
[MRG + 1] Handle unavailable RATS

### PR DESCRIPTION
**Pull request by salma1601**
This PR fixes the first point of #69, because RATS will not be available on travis. It will also allow testing of nilearn mask based on histogram

### CODE REVIEW

**Comment by salma1601** [comment]
@nadkarni-na Could you please give this one a first round review ?
I tried to design a brain extraction procedure not relying on RATS, using nilearn and some morphological operations.
It will not do as good as RATS in some situations, however this is important to
1- raise awareness to the user when they use RATS that they must cite it
2- allow the default pipelines to be tested on travis

**Comment by nadkarni-na** [comment]
message me when you have finished editing, and have tested this on three different datasets (Pauline rats, Sawiak mouse lemurs and DCLK3 mice provide a good variety). we need to know what the full consequences are on registration quality.

as a more general point, it is not a good idea to take procedures that work and make them worse and/or more complicated or even break them just to fit some external target or requirement that is not appropriate to the project at this stage. despite ANTS being far more mature and well-known, having unknown coverage, unknown build and failed codeship has not stopped them. it is better to make these changes later, which would be the same amount of effort, after having made a complete product that works.

**Comment by salma1601** [comment]
The most important point for me is that the user should be completely aware of turning on the use of RATS. The user is **obliged** to cite 2 papers for this use and I want him to be aware each time he uses it. That is said, nothing prevents an aware user to use RATS.

>as a more general point, it is not a good idea to take procedures that work and make them worse and/or more complicated or even break them 
The documentation can be more explicit, saying that RATS may give more precise results but needs to be personally installed and cited.

> just to fit some external target or requirement that is not appropriate to the project at this stage.

I think it is important: we need to have our pipelines automatically tested each time a code change is done. This does not prevent more testing on data for important changes, but little changes also can just break the code.

>Pauline rats, Sawiak mouse lemurs and DCLK3 mice provide a good variety

Already tested on Pauline's and Zurich data. I plan to test them on our lemurs and mice

**Comment by nadkarni-na** [comment]
The user will already be aware of the need to cite RATS. It's all over the code and the website, and can be made more explicit if needed, including in terminal output. This is accepted practice elsewhere.

Make sure the results of Pauline rats, Zurich mice, DCLK3 mice and sawiak lemurs (the IR-FSE acquisitions from 2005) are as good as if using RATS. The way the code is written, using nilearn functions to mask the brain will be the default so this has to be tested on the entire range of data where RATS is already known to work well enough. This includes testing on individual fMRI-to-template datasets of poor quality, plus partial coverage acquisitions (test data for this is in /home/Promane/2014-ROMANE/5_Experimental-Plan-Experiments-Results/mouse/ASH). Otherwise RATS should be the default, which makes all of this pointless (why deliberately choose the poorer-performing option as the default?). This was what was done to test the shell scripts any time there was a change. The other advantage of all this testing is that if you have found a way to use nilearn to do rodent brain extraction, a paper could be written on it.

The only test that matters in the end is the correctness of the images and other output. The old code for registration.anats_to_common, excepting RATS, would have passed Travis and coverage and still not worked. Only a month of chasing around the idiosyncrasies of nipype's bureaucracy made it produce results as good as the shell scripts.

**Comment by salma1601** [comment]
>The user will already be aware of the need to cite RATS. It's all over the code and the website, and can be made more explicit if needed, including in terminal output. This is accepted practice elsewhere.

Ok, let's make it clearer.

>Make sure the results of Pauline rats, Zurich mice, DCLK3 mice and sawiak lemurs (the IR-FSE acquisitions from 2005) are as good as if using RATS. The way the code is written, using nilearn functions to mask the brain will be the default so this has to be tested on the entire range of data where RATS is already known to work well enough. This includes testing on individual fMRI-to-template datasets of poor quality, plus partial coverage acquisitions (test data for this is in /home/Promane/2014-ROMANE/5_Experimental-Plan-Experiments-Results/mouse/ASH). 

I don't think I will have time to do such exhaustive testing. I finished testing on some lemurs and mice and it's OK

>Otherwise RATS should be the default,(why deliberately choose the poorer-performing option as the default?)

Well, we already don't perform nonlinear registration because it's very time consuming. The default for me should be something that works not so bad in 80% of cases. Anyway, I am OK with changing the default if it is said all over the code that RATs can be replaced

> which makes all of this pointless 

No, it's necessary: for tests ! For the moment the pipeline itself is not tested !
>if you have found a way to use nilearn to do rodent brain extraction, a paper could be written on it.

Well, you know what I think about publications ... It doesn't take more than 150 lines of code so that is not so big deal I think.

>The only test that matters in the end is the correctness of the images and other output. The old code for registration.anats_to_common, excepting RATS, would have passed Travis and coverage and still not worked. Only a month of chasing around the idiosyncrasies of nipype's bureaucracy made it produce results as good as the shell scripts.

Agree, but this is an argument to improve our tests and coverage !

**Comment by salma1601** [comment]
@nadkarni-na finished tests on (mouse/rat/lemur) data and put the default to RATS.

**Comment by nadkarni-na** [comment]
If RATS is set as the default, I'll start reviewing the code carefully. Might be a few days before am finished though.

**Comment by salma1601** [comment]
Yes RATS has been set  as the default. Ok thanks !

**Pull request merged**
