### PR TITLE
[WIP] Functional to template registration

### PR DESCRIPTION
**Pull request by salma1601**
based on the most simple animal data structure, with anat, func, id as attributes. Remember to add a template output attribute

### CODE REVIEW

**Comment by salma1601** [comment]
I want to merge this one because we need it for the course. It has not been fully tested on data, I am delaying this to tomorrow.
@nadkarni-na are you OK ?

**Comment by salma1601** [comment]
just tested it on zurich data and not fully satisfied, but since registration is not a success on this data we can't rely on it

**Comment by nadkarni-na** [comment]
then test it on DICOMs, assuming there is an equivalent to IDprotocols somewhere

**Comment by salma1601** [comment]
you mean their dicoms ?

**Comment by nadkarni-na** [comment]
ours. mouse lemurs, mice, rats, anything

**Comment by salma1601** [comment]
Ah OK. Dicom to nifti is not merged yet but I am going to test it on our niftis, just after your dicom conversion (the raw anat and func)

**Comment by nadkarni-na** [comment]
Then review/edit and merge it because it is important for the course to show that we can do everything starting with DICOMs. Especially since ironically those NIfTIs were generated with it

**Comment by salma1601** [comment]
I am merging for the course, and debugging the orientation bug afterwards

**Pull request merged**
