### PR TITLE
[WIP] New design: relate preprocessing to structural image

### PR DESCRIPTION
**Pull request by salma1601**
- [X] `TemplateRegistrator` object with anat and template enteries, exposing segmentation, normalization and modality normalization methods
- [X] add inverse_normalization to transform template/atlas to native space
- [x] test same results as functional and structural normalization
- [ ] add CBF computation example

### CODE REVIEW

**Comment by salma1601** [comment]
@nadkarni-na what is the CBF to be plotted: the rCBF or the CBF maps ?

**Comment by nadkarni-na** [comment]
CBF is the priority

**Comment by salma1601** [comment]
The native map of CBF is strange: intensity is less than 3 inside the brain while for rCBF it looks appropriate (around 100)
is this normal ?

**Comment by nadkarni-na** [comment]
nope; they're either the other way round, the multiplier or lambda have been badly specified or something went really wrong with the tagging

**Comment by salma1601** [comment]
sorry, it was my fault, I mixed up rCBF and CBF. Now it is in the correct range.
Does this look like your expectations (CBF averaged on 10 BECIM mice)
mean_cbf

**Comment by nadkarni-na** [comment]
Yep!

**Comment by salma1601** [comment]
are there interesting regions to compare cbf within ?

**Comment by nadkarni-na** [comment]
For that study, no; whole brain is best.

**Comment by salma1601** [comment]
It's rather for illustrating that we can extract values. I have around 150 values for instance in the hypocampus, amygdala, hypothalamus

**Comment by nadkarni-na** [comment]
Hippocampus

**Comment by salma1601** [comment]
hippocampal_cbf

**Comment by salma1601** [comment]
Closing, as superseeded by #101

**Pull request closed without merging**
