### PR TITLE
[MRG + 1] try basic afni install

### PR DESCRIPTION
**Pull request by salma1601**
This aims to install AFNI on neurodebian so that AFNI based tests can be run
- [X] install AFNI
- [X] remove FSL dependencies
- [X]  allow optional use of nilearn.compute_epi_mask for mask computation

### CODE REVIEW

**Comment by nadkarni-na** [comment]
Is this substantially easier than installing from the [AFNI package](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu16.html)?

**Comment by salma1601** [comment]
yes: just one sudo apt-get install afni ! with possibly some wget for conda environement, but for neurodebian it is straightforward!
Note that this is just to run tests on travis with AFNI commands

**Comment by salma1601** [comment]
@nadkarni-na I think I am done with this one ! Now we have tests for all the pipelines !
All this can be improved in the future but for the moment I think it is quite sufficient.
Could you please give it a review ?

**Comment by salma1601** [comment]
@nadkarni-na could you please review this PR ? I am working on other branches and waiting for this one

**Comment by salma1601** [comment]
Thanks ! merging

**Pull request merged**
