### PR TITLE
[MRG] keep mvt parameters in outputs

### LINKED ISSUE #57: movement parameters
registration.fmri_sessions_to_template does not store them by default

guess that's the case for coregister_fmri_session too

### PR DESCRIPTION
**Pull request by salma1601**
fix #57

### CODE REVIEW

**Comment by salma1601** [comment]
@nadkarni-na  could you have a look please ?

**Comment by salma1601** [comment]
What do you mean all three possible files? I am just keeping the 1Dfile.1D

**Comment by nadkarni-na** [comment]
3dvolreg can output three formats, if we only need one that's fine too, the shell script put out all three just in case of need to avoid having to dig around the afni py scripts if the format needed to be changed

**Comment by salma1601** [comment]
well, for the moment we always used the 1Dfile for functional connectivity and checking the amount of movement, so I am +1 for saving just this 1Dfile.

**Comment by salma1601** [comment]
merge ?

**Comment by nadkarni-na** [comment]
yes

**Pull request merged**
