### PR TITLE
[MRG+1] anattotemplate.bash in python

### PR DESCRIPTION
**Pull request by salma1601**
TODO

- [x]  ANTS N4BiasFieldCorrection
- [x] RATS
- [x] AFNI cat_matvec

### CODE REVIEW

**Comment by salma1601** [comment]
a draft working pipeline. Waiting for

- [ ] nipype merging NwarpCat and fixing Qwarp outputs bug
- [ ] using the correct pipeline parameters (input paths)
- [ ] working the doc: split in subsections and write relevant comments

**Comment by salma1601** [comment]
Hourrah ! tests passed
@nadkarni-na I am going to merge this, did you have a look at the template ?

**Comment by nadkarni-na** [comment]
Just looked at it now. One of the mice is very badly aligned, and another hasn't worked too well. In any case I need >=6 to judge better...

**Comment by salma1601** [comment]
Ok, I will send you with 6 mice when it is finished. Meanwhile I would like to merge this and update the documentation in the web site. +1 for merging ?

**Comment by nadkarni-na** [comment]
If the calculation was done based on just four input mice, it might be bad just for that reason. So few inputs results in noisy initial images, which makes subsequent analyses worse. I you want to make the test quicker, it's best to use >10 at lower resolution. The input data are at 100um, 200um works well for mice too, and the files are 1/8 the size. Yep merge though I cannot guarantee it actually works unless the tests are done with many mice and not just XNAT_CSD_MRI_MOUSE. Can set up a test on Monday.

**Comment by salma1601** [comment]
Ok, I am going to merge then test with more mice and 200um resolution. Thanks !

**Pull request merged**
