### PR TITLE
fetcher for Rat Waxholm template and restyling

### PR DESCRIPTION
**Pull request by salma1601**
this PR includes many changes. Not advised to do so but because the course rush.

- fetcher for waxholm rat altas and template
- restyling for scanner converters
- update of the doc
- adding function to compare obliquities of 2 images

### CODE REVIEW

**Comment by salma1601** [comment]
@nadkarni-na Is there a particular reason why you use double `_` in nifti filenames converted from DICOM?

**Comment by nadkarni-na** [comment]
to better distinguish the different components of the file name (it's rare that someone will name an animal or protocol with a double underscore, so it seemed like a reasonable delimeter)

**Comment by salma1601** [comment]
I was asking because I didn't rename my niftis, then tried to run the coregistration pipeline, and got an error with AFNI's `3dcopy`
>** FATAL ERROR: Illegal old dataset name! - EXIT

this seemed related to AFNI not satisfied with my filename, because everything works perfectly when I replace the double underscores by a single one
https://afni.nimh.nih.gov/afni/community/board/read.php?1,71176,71178#msg-71178

so I am +1 for using a single underscore

**Comment by nadkarni-na** [comment]
I don't process those files with their original names, I use an automatic renaming module first

**Comment by salma1601** [comment]
Yes I know, but since I am separating bricks and letting the user choose which DICOM tag he wants to encapsulate, he can use his own names. I want to avoid this AFNI error because it may be difficult to track.

**Comment by nadkarni-na** [comment]
Then do os.environ['AFNI_ALLOW_ARBITRARY_FILENAMES'] = 'YES'  (https://afni.nimh.nih.gov/afni/community/board/read.php?1,71176,71179#msg-71179, next message in the same thread), this is in any case necessary as it is possible to enter characters at the MRI console that would trip up AFNI. I've seen French characters more than once in input data, that also causes AFNI to stop.

**Comment by nadkarni-na** [comment]
The only other option is a pythonic equivalent of something like the unix command tr -cd [:alnum:]-_

**Comment by salma1601** [comment]
Is there any benefit of `AFNI_ALLOW_ARBITRARY_FILENAMES` being NO by default ?

**Comment by nadkarni-na** [comment]
Quoting AFNI README.environment:

"
----------------------------------------
Variable: AFNI_ALLOW_ARBITRARY_FILENAMES
----------------------------------------
Normally, AFNI checks output filenames for 'bad' characters, which are defined as control characters and ASCII characters that will cause trouble on the Unix command line ('*', '$', etc.).  'Bad' filenames will not be allowed by most AFNI programs.  If, for some reason, you want to use such filenames, set this variable to YES.  Don't blame me if you get into trouble with such filenames!
"

From experience even the character é trips up the software. If nipype can deal with these then we should have a liberal attitude towards weird characters. If not, then the DICOM converter and/or every IO function needs to include a block and/or filter for strange characters.

**Comment by salma1601** [comment]
OK, then I would
- use default "good" filenames, starting from DICOMs and including the preprocessing outputs.
- let the user define `AFNI_ALLOW_ARBITRARY_FILENAMES`, with a default to keeping AFNI's default behavior.

Hence, if the user wants to force his "fancy" names, he can do that and then change the `AFNI_ALLOW_ARBITRARY_FILENAMES` with his own responsability

**Comment by nadkarni-na** [comment]
ok

**Comment by salma1601** [comment]
Merging ! coverage decreased a little but will be dealt with in the future

**Pull request merged**
