### PR TITLE
[MRG + 1] fix qwarp not initialized

### LINKED ISSUE #72: registration.anats_to_common can't go beyond level 8, partially ignores minpatch
Am still having a problem mentioned in #65; for some reason, during the -minpatch loops, -maxlev n is added to the end of the 3dQwarp command passed to the shell even though -maxlev should not appear at all (as seen both by ps -aux in real time, and also doing 3dinfo on the resulting images). n is the maxlev used in the final maxlev loop. The effect is also visible in the nipype verbose output.

The end result is that whatever minpatch(es) is/are supplied, the contradictory -maxlev n creates a contradiction. The decision 3dQwarp makes is just to advance 1 level beyond n.

I've got this problem with three very different sets of data. The logs are quite large and the datasets not public, @salma1601 when you are at MIRCen msg me then I'll DM you.

### PR DESCRIPTION
**Pull request by salma1601**
fix  #72

### CODE REVIEW

**Comment by salma1601** [comment]
@nadkarni-na needs a review to merge this one. Thanks !

**Comment by nadkarni-na** [comment]
Comments need to be added to explain why qwarp2 has been introduced.

**Comment by salma1601** [comment]
added comment

**Comment by salma1601** [comment]
thanks, merging

**Pull request merged**
