### PR TITLE
[WIP] multimodal registration

### PR DESCRIPTION
**Pull request by salma1601**
try addressing #49

### CODE REVIEW

**Comment by salma1601** [comment]
@nadkarni-na I need some help here. I implemented CEST coregistration of anat removing the per slice registration and the slice timing correction and keeping all the rest. Then for registration to the template I just apply the catenated anat to func and anat to template transforms. Is this OK ?

**Comment by nadkarni-na** [comment]
If "keeping all the rest" includes the part where the CEST image is processed by 3dWarp to be in the same obliquity plane as the anat, then yes it's OK.

**Comment by salma1601** [comment]
Yes, and it includes also unifization ...
so now I want to move to perfusion. If I remember correctly it is exactly the same as functional, a part from the fact that we don't use an average image but compute a per slice registration for each time point ?

**Comment by nadkarni-na** [comment]
This is a long answer but a short one would be too ambiguous. For perfusion, the image used for per-slice registration has a complicated origin, but it's final geometry is the same as for a single perfusion volume which leads to a short-term testing solution.

As an example, our standard perfusion protocol in mice produces a 4D dataset of 160x96x5x32. 160x96 is the slice matrix, 5=slices and there are 32 volumes of the 2 selective/non-selective tagging conditions x 16 tag delays. By non-linear fitting in R to the 16 tag delays (found in DICOM metadata), the 32 volumes are processed to produce 14 statistical volumes of 160x96x5 each: 2 tagging conditions x 3 fitted parameters (bias, M0 and T1) x 2 statistics (mean and standard deviation), plus an rCBF image calculated from the mean T1 images and a CBF image calculated from the mean T1 images and other input parameters.

**The two M0 mean images are averaged, and this average mean M0 is used for per-slice registration.**

It is going to be 1-2 weeks before I start integrating the perfusion processor as this will likely involve learning rpy2. I could do it quickly by executing in the R interpreter directly from python but apparently rpy2 can be a better interface.

**In the meantime, for the purposes of testing, the first of the 32 volumes is a perfect substitute for the average of the two M0 mean images.** After doing per-slice registration on it, the resulting warps would need to be applied to all the other statistical images and the original 4D dataset too.

**Comment by salma1601** [comment]
looks like things are complicated for ASL. Moreover when I worked on human ASL data, we were not using the standard realignment procedure as it can identify tagging difference as motion and results in 'zigzag' estimated mvt parameters. Did yo handle this aspect ?

**Comment by nadkarni-na** [comment]
due to signal extinction and extremely low "temporal" resolution, we don't do any realignment at all as it cannot be made to work (similar to the case of CEST). the assumption is made that the individual does not move. the acquisition protocol we use is not used in humans, partially because of the need to assume this

**Comment by nadkarni-na** [comment]
which reminds me I missed out something earlier...the CEST data must not be realigned, just assume that the subject does not move

**Comment by salma1601** [comment]
I didn't realign the CEST, but left the option of rigid-body registration between anat and cest

**Comment by nadkarni-na** [comment]
yep that's OK

**Comment by salma1601** [comment]
and unifization of cest, does it make sense ?

**Comment by nadkarni-na** [comment]
yes, all of our data (and the vast majority of what is in the literature) uses surface receivers so that need is protocol-independent. there is admittedly a theoretical need to make bias-correction optional anyway, but that can await Release 2.

**Comment by salma1601** [comment]
Ok

**Comment by salma1601** [comment]
@nadkarni-na why is it necessary here to compute the inverse warp ?
https://github.com/sammba-mri/sammba-mri/blob/master/sammba/registration/func.py#L412

**Comment by nadkarni-na** [comment]
In case a need arises to apply a mask or atlas segmentation from the template back into raw image space. These per-slice inverted warps occupy little space and are quick to compute so it's a harmless addition.

**Comment by salma1601** [comment]
but I have some cases the inversion fails so it makes the program crashes

**Comment by nadkarni-na** [comment]
That happens sometimes, in the bash version the failure is caught and discarded and the script continues

**Comment by salma1601** [comment]
Can't the inverse warp be computed aftewards directly from the warps ?

**Comment by nadkarni-na** [comment]
Yes but it's not as efficient

**Comment by salma1601** [comment]
from AFNI 3dQwarp doc 
>               * You can easily compute the inverse later, say by a command like
                  3dNwarpCat -prefix Z_WARPINV 'INV(Z_WARP+tlrc)'
                 or the inverse can be computed as needed in 3dNwarpApply, like
                  3dNwarpApply -nwarp 'INV(Z_WARP+tlrc)' -source Dataset.nii ..

I prefer this logic, because I am in any case removing most of intermediate output files when no caching.
This is simpler than catching a possible error and dealing with it

**Comment by nadkarni-na** [comment]
That command takes longer than inverting a warp that's already in the RAM, and replaces one extra flag with several supplementary code lines. The original logic is simpler, more computationally-efficient and future-proofed. It's only disadvantage is leaving a slice count number of files, which is not a big problem.

**Comment by salma1601** [comment]
may be it's longer for those who need it, but it will be shorter for those who does not need it.
Anyway, for the moment we don't have a `template_to_native` function so in any case I don't see it's use within sammba. When we will have such a function, we can think carefully, compare computation time and code readability.

**Comment by nadkarni-na** [comment]
I'm hesitant to interpret this comment as it was written when I was still not sure how I wanted to do the per-slice registration, but I'll try anyway.

3dQwarp works best on isotropic voxels and larger matrix sizes (plus maybe square/cubic matrices too, which is not in the instructions but from memory can be the case in real-world situations).This extends to the stability of warp inversion.

The resampling steps were introduced to ensure isotropic voxels (to a user-set resolution), and so potentially indirectly increasing the matrix size too (if the resolution given is fine enough). However, it doesn't make the matrix square, though I cannot remember if this really helps..

**Comment by salma1601** [comment]
Ok so if understand well it is important to resample even if we don't want to inverse the warp ?

**Comment by nadkarni-na** [comment]
yes, definitely

**Comment by salma1601** [comment]
closing, as fixed by #110

**Pull request closed without merging**
