### PR TITLE
replace nipype with subprocess

### PR DESCRIPTION
**Pull request by nadkarni-na**
This will have to be modified as it's an ugly solution, am submitting because:
1) @garincle needs the code example now
2) it narrows down the origins of issue #71 to the nipype interface

### CODE REVIEW

**Comment by salma1601** [comment]
can you give a traceback ? I don't understand the issue

**Comment by nadkarni-na** [comment]
there is no traceback to give as the script does not quit with an error at this stage. it quits at the first linear registration which is done from one empty image to another, causing 3dAllineate to fail. following the images back, as explained in issue #71, it turns out that the image center of the undump output is incorrectly set by refit(), causing all CoM-shifted images to be empty since all voxels are resliced to outside the FOV

**Comment by salma1601** [comment]
and using subprocess to launch the same command as nipype fixes the problem ?

**Comment by nadkarni-na** [comment]
yep, on finn and my laptop

**Comment by nadkarni-na** [comment]
the caveat being it's not been tested on many datasets, though 3dUndump/3drefit never had this prob in the bash scripts, so it should be fine. if it isn't I'd be lost to give an explanation

**Comment by salma1601** [comment]
but with bash now in this data sample it doesn't have a problem neither right ?

**Comment by nadkarni-na** [comment]
that is the case, directly executing the 3drefit command in bash also gave the correct result

**Comment by salma1601** [comment]
is the command line
`3drefit -xorigin cen -yorigin cen -zorigin cen image.nii.gz`

**Comment by salma1601** [comment]
I need your data sample. Can't reproduce any difference between command line 3drefit and nipype wrapping

**Comment by nadkarni-na** [comment]
https://www.dropbox.com/s/nu0pt5vr1zr256y/anat_nx_x.nii.zip?dl=0

**Comment by nadkarni-na** [comment]
resolved by #89

**Pull request closed without merging**
