### PR TITLE
missing draft docs

### PR DESCRIPTION
**Pull request by nadkarni-na**

### CODE REVIEW

**Comment by salma1601** [comment]
I am a little lost, because I see `.bash`, `.r` and things without a suffix. Is `MRIT2_extrcen` for instance a command ?

**Comment by nadkarni-na** [comment]
I forgot to add .bash that that and the next six files

**Comment by salma1601** [comment]
Sorry, is this work in progress ?

**Comment by nadkarni-na** [comment]
what isn't? less philosophically, better to discuss my commits when you get back. esp. as they are only to dev. hope your hols are good!!!

**Comment by salma1601** [comment]
OK. Yes relaxing holidays, thanks ! see you

**Pull request merged**
