### PR TITLE
[MRG+1] Bias correction order

### PR DESCRIPTION
**Pull request by salma1601**
added a parameter `brain_from_biased` in anatomical registration, to let the user choose if the brain extraction should be done from bias corrected or not images.
I didn't find a better naming for this parameter that uses maximum number of 3 words, so better suggestions are welcome

### CODE REVIEW

**Comment by salma1601** [comment]
I also removed the rbt parameters because I fear users get submerged by too many parameters. Also, playing with these 3 numbers didn't solve messy brain extraction from what I tried.

**Comment by salma1601** [comment]
@nadkarni-na could you please have a look at this one if it is ready for merge ?

**Comment by nadkarni-na** [comment]
strictly speaking it should be something like brain_from_raw or brain_from_original; calling it biased assumes input images are always biased, which is not the case. otherwise, on a quick read code looks fine

**Comment by salma1601** [comment]
You are right ! Changing to `brain_from_raw`, thanks for the name !

**Pull request merged**
